new Levels
opensource-ninjas/tower-defense pull request #40
Opened 2019-06-04 10:48 UTC by OZadok

2019-06-05 13:32 UTC, Coder-DG requested changes
Hi, please remove all the .idea/* files first.

2019-06-05 13:32 UTC, davidginzbourg commented
Also note that you haven't passed the `flake8` tests.

2019-06-05 14:56 UTC, Arcticactus commented
This fixes #38

2019-06-11 18:47 UTC, Coder-DG approved these changes

2019-06-13 11:58 UTC, merged